"""empty message

Revision ID: 79966e20b780
Revises: 5fd3f9b20ee6
Create Date: 2023-05-22 14:15:01.688980

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '79966e20b780'
down_revision = '5fd3f9b20ee6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('options', schema=None) as batch_op:
        batch_op.alter_column('optionname',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('options', schema=None) as batch_op:
        batch_op.alter_column('optionname',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###
