"""empty message

Revision ID: 9bce0e488e4c
Revises: 
Create Date: 2023-05-21 17:58:07.640287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bce0e488e4c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teams',
    sa.Column('teamid', sa.Integer(), nullable=False),
    sa.Column('teamname', sa.String(length=20), nullable=False),
    sa.Column('creator', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creator'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('teamid')
    )
    op.create_table('members',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.teamid'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.UniqueConstraint('team_id', 'user_id', name='uix_1')
    )
    op.create_table('polls',
    sa.Column('pollid', sa.Integer(), nullable=False),
    sa.Column('pollname', sa.String(length=20), nullable=True),
    sa.Column('teamid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['teamid'], ['teams.teamid'], ),
    sa.PrimaryKeyConstraint('pollid')
    )
    op.create_table('options',
    sa.Column('optionid', sa.Integer(), nullable=False),
    sa.Column('optionname', sa.String(length=20), nullable=False),
    sa.Column('votes', sa.Integer(), nullable=False),
    sa.Column('pollid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pollid'], ['polls.pollid'], ),
    sa.PrimaryKeyConstraint('optionid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('options')
    op.drop_table('polls')
    op.drop_table('members')
    op.drop_table('teams')
    op.drop_table('users')
    # ### end Alembic commands ###
